version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=5174
      - CHOKIDAR_USEPOLLING=true
